name: fooddelivery
description: A new Flutter application.

# publish_to: 'none' 

version: 2.0.3+15

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.5
  cloud_firestore: ^4.16.1
  flutter_mobx: ^2.2.1+1
  nb_utils: ^7.0.0
  firebase_messaging: ^14.8.1
  flutter_local_notifications: ^17.0.1
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^4.19.1
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.6
  google_maps_flutter: ^2.2.8
  flutter_vector_icons: ^2.0.0
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  package_info_plus: ^7.0.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.8
  infinite_scroll_pagination: ^4.0.0
  upgrader: ^10.2.0
  audio_video_progress_bar: ^2.0.2
  audioplayers: ^6.0.0
  country_code_picker: ^3.0.0
  share: ^2.0.4
  avatar_glow: ^3.0.1
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1
  audio_session: ^0.1.19
  flutter_typeahead: ^5.2.0
  firebase_pagination: ^3.1.0

  intl: any
  http: any
  path_provider: any
  sliding_up_panel: any
  path: any
  mobx: any
  firebase_core: ^2.29.0
  audio_waveforms: ^1.0.5
  chat_bubbles: ^1.5.0
  smooth_page_indicator: ^1.1.0
  timeago: ^3.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  change_app_package_name: ^1.1.0

# dependency_overrides:
#     firebase_core_platform_interface: 4.5.1

flutter:

  uses-material-design: true

  assets:
    - assets/placeholder.jpg
    - assets/food/
    - assets/
    - assets/flag/
    - lang/

